
# general.import = [
#     "./themes/themes/tokyo_night.toml"
# ]
general.live_config_reload = true

[font]
size = 16

[window]
padding.x = 10
padding.y = 10
opacity = 1.0

[colors]
primary.background = "#000000"

